### ISSUE TITLE
WorldEdit its not running Bukkit 1.4.2 WE 5.4.5

### ISSUE THREAD

**Issue by LadyCailin** [LadyCailin/TestIssueUploader#154]
WORLDEDIT-2242 - Reported by snAke2xLc on 2012-11-13 20:01:42 UTC

have problem running World edit dont know why maybe you can me help (sry 4 bad english)

C:\Users\Freak\Desktop\Minecraft Server 2>java -Xms1024M -jar craftbukkit.jar -o true
208 recipes
27 achievements
20:54:43 [INFO] Starting minecraft server version 1.4.2
20:54:43 [INFO] Loading properties
20:54:43 [INFO] Default game type: SURVIVAL
20:54:43 [INFO] Generating keypair
20:54:44 [INFO] Starting Minecraft server on 5.76.28.241:25565
20:54:44 [INFO] This server is running CraftBukkit version git-Bukkit-1.4.2-R0.2-b2455jnks (MC: 1.4.2) (Implementing API version 1.4.2-R0.2)
20:54:44 [INFO] [WorldEdit] Loading WorldEdit v5.4.5
20:54:44 [INFO] [SafeCreeper] Loading SafeCreeper v1.2
20:54:44 [INFO] [dynmap] Loading dynmap v0.90-1347
20:54:44 [INFO] [SafeCreeper] Enabling SafeCreeper v1.2
20:54:44 [INFO] [SafeCreeper] No supported permissions system found! Permissions disabled!
20:54:44 [INFO] [SafeCreeper] Loading config files...
20:54:44 [INFO] ----- Bukkit Auto Updater -----
20:54:44 [INFO] It appears that you're running a Beta Build, when you've specified in bukkit.yml that you prefer to run Recommended Builds.
20:54:44 [INFO] If you would like to be kept informed about new Beta Build releases, it is recommended that you change 'preferred-channel' in your bukkit.yml to 'beta'.
20:54:44 [INFO] With that set, you will be told whenever a new version is available for download, so that you can always keep up to date and secure with the latest fixes.
20:54:44 [INFO] If you would like to disable this warning, simply set 'suggest-channels' to false in bukkit.yml.
20:54:44 [INFO] ----- ------------------- -----
20:54:44 [INFO] [SafeCreeper] Global config file loaded
20:54:44 [INFO] [SafeCreeper] 2 world config files loaded
20:54:45 [INFO] [SafeCreeper] Safe Creeper v1.2 Enabled
20:54:45 [INFO] Preparing level "world"
20:54:45 [INFO] Preparing start region for level 0 (Seed: 8778414763692030089)
20:54:46 [INFO] Preparing spawn area: 81%
20:54:46 [INFO] Preparing start region for level 1 (Seed: -3375529530685505380)
20:54:47 [INFO] Preparing start region for level 2 (Seed: -3375529530685505380)
20:54:47 [INFO] Preparing spawn area: 52%
20:54:47 [INFO] [WorldEdit] Enabling WorldEdit v5.4.5
20:54:47 [SEVERE] Error occurred while enabling WorldEdit v5.4.5 (Is it up to date?)
while scanning for the next token
found character         '\t' that cannot start any token
 in "<reader>", line 48, column 1:
                        - worldedit.chunkinfo
    ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:179)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:535)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146)
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:203)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:158)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:160)
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:123)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:106)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:480)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:423)
        at com.sk89q.util.yaml.YAMLProcessor.load(YAMLProcessor.java:112)
        at com.sk89q.wepif.PermissionsResolverManager.loadConfig(PermissionsResolverManager.java:190)
        at com.sk89q.wepif.PermissionsResolverManager.<init>(PermissionsResolverManager.java:103)
        at com.sk89q.wepif.PermissionsResolverManager.initialize(PermissionsResolverManager.java:68)
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:91)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:272)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:254)
        at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:320)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:299)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:258)
        at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:141)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:400)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)
20:54:47 [INFO] [dynmap] Enabling dynmap v0.90-1347
20:54:47 [INFO] [dynmap] Using Bukkit Permissions (superperms) for access control
20:54:47 [INFO] [dynmap] Web interface permissions only available for online users
20:54:48 [INFO] [dynmap] Loaded 21 shaders.
20:54:49 [INFO] [dynmap] Loaded 82 perspectives.
20:54:49 [INFO] [dynmap] Loaded 12 lightings.
20:54:49 [INFO] [dynmap] Web server started on address 0.0.0.0:8123
20:54:49 [INFO] [dynmap] version 0.90-1347 is enabled - core version 0.90-373
20:54:49 [INFO] [dynmap] Loaded 3 maps of world 'world'.
20:54:49 [INFO] [dynmap] Loaded 2 maps of world 'world_nether'.
20:54:49 [INFO] [dynmap] Loaded 2 maps of world 'world_the_end'.
20:54:49 [INFO] [dynmap] Enabled
20:54:49 [INFO] Server permissions file permissions.yml is empty, ignoring it
20:54:49 [INFO] Done (4,538s)! For help, type "help" or "?"

>hope you guys can help me

**Comment by LadyCailin** [comment]
Comment by sk89q on 2012-11-13 20:35:47 UTC

You made a mistake in wepif.yml. Normally you do not have to edit that file if you already have a permissions plugin. I recommend deleting it to reset it.
