### ISSUE TITLE
Set selection with random pattern

### ISSUE THREAD

**Issue by LadyCailin** [LadyCailin/TestIssueUploader#162]
WORLDEDIT-2250 - Reported by Jeffrey.Angenent on 2012-11-15 16:52:36 UTC

{code:title=Command}//set 33%:diamondore,33%ironore,34%coalore```
{code:title=Console Log}17:49:00 [SEVERE] java.lang.StringIndexOutOfBoundsException: String index out of range: 0
17:49:00 [SEVERE] 	at java.lang.String.charAt(Unknown Source)
17:49:00 [SEVERE] 	at com.sk89q.util.StringUtil.lookup(StringUtil.java:291)
17:49:00 [SEVERE] 	at com.sk89q.worldedit.blocks.BlockType.lookup(BlockType.java:263)
17:49:00 [SEVERE] 	at com.sk89q.worldedit.blocks.BlockType.lookup(BlockType.java:249)
17:49:00 [SEVERE] 	at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:387)
17:49:00 [SEVERE] 	at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:355)
17:49:00 [SEVERE] 	at com.sk89q.worldedit.WorldEdit.getBlock(WorldEdit.java:549)
17:49:00 [SEVERE] 	at com.sk89q.worldedit.WorldEdit.getBlockPattern(WorldEdit.java:622)
17:49:00 [SEVERE] 	at com.sk89q.worldedit.commands.RegionCommands.set(RegionCommands.java:74)
17:49:00 [SEVERE] 	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
17:49:00 [SEVERE] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
17:49:00 [SEVERE] 	at java.lang.reflect.Method.invoke(Unknown Source)
17:49:00 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:522)
17:49:00 [SEVERE] 	at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:241)
17:49:00 [SEVERE] 	at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:172)
17:49:00 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:509)
17:49:00 [SEVERE] 	at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
17:49:00 [SEVERE] 	at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1339)
17:49:00 [SEVERE] 	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:197)
17:49:00 [SEVERE] 	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
17:49:00 [SEVERE] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:185)
17:49:00 [SEVERE] 	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:502)
17:49:00 [SEVERE] 	at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:917)
17:49:00 [SEVERE] 	at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:835)
17:49:00 [SEVERE] 	at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:812)
17:49:00 [SEVERE] 	at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
17:49:00 [SEVERE] 	at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
17:49:00 [SEVERE] 	at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:112)
17:49:00 [SEVERE] 	at net.minecraft.server.ServerConnection.b(SourceFile:39)
17:49:00 [SEVERE] 	at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
17:49:00 [SEVERE] 	at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
17:49:00 [SEVERE] 	at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
17:49:00 [SEVERE] 	at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
17:49:00 [SEVERE] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
17:49:00 [SEVERE] 	at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)```

**Comment by LadyCailin** [comment]
Comment by wizjany on 2012-11-22 17:53:01 UTC

You have a colon between the first % and diamondore
