### ISSUE TITLE
Unknown exception while loading custom mob drop definitions

### ISSUE THREAD

**Issue by LadyCailin** [LadyCailin/TestIssueUploader#264]
CRAFTBOOK-2252 - Reported by chevyman142000 on 2012-11-18 05:14:11 UTC

I get the following error when starting my server.

00:03:38 [SEVERE] Unknown exception while loading custom mob drop definitions
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.sk89q.craftbook.mech.CustomDropManager.loadDropDefinitions(CustomDropManager.java:110)
        at com.sk89q.craftbook.mech.CustomDropManager.<init>(CustomDropManager.java:72)
        at com.sk89q.craftbook.MechanismsConfiguration.load(MechanismsConfiguration.java:86)
        at com.sk89q.craftbook.BaseConfiguration.<init>(BaseConfiguration.java:24)
        at com.sk89q.craftbook.MechanismsConfiguration.<init>(MechanismsConfiguration.java:50)
        at com.sk89q.craftbook.bukkit.MechanismsPlugin.onEnable(MechanismsPlugin.java:74)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:270)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:252)
        at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:320)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:299)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:258)
        at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:147)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:398)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)

**Comment by LadyCailin** [comment]
Comment by chevyman142000 on 2012-11-18 05:19:28 UTC

This is using craftbukkit 1.4.4 and version #1279-eb6dc26 of craftbook.

**Comment by LadyCailin** [comment]
Comment by me4502 on 2012-11-18 06:17:44 UTC

That looks like something that'd be caused by invalid recipes.

**Comment by LadyCailin** [comment]
Comment by me4502 on 2012-11-18 06:20:31 UTC

Fixed.

**Comment by LadyCailin** [comment]
Comment by chevyman142000 on 2012-11-18 06:28:00 UTC

I get the following using #1281 on startup

01:25:36 [SEVERE] Unknown exception while loading custom mob drop definitions
java.lang.ArrayIndexOutOfBoundsException: 0
        at com.sk89q.craftbook.mech.CustomDropManager.loadDropDefinitions(CustomDropManager.java:112)
        at com.sk89q.craftbook.mech.CustomDropManager.<init>(CustomDropManager.java:72)
        at com.sk89q.craftbook.MechanismsConfiguration.load(MechanismsConfiguration.java:86)
        at com.sk89q.craftbook.BaseConfiguration.<init>(BaseConfiguration.java:24)
        at com.sk89q.craftbook.MechanismsConfiguration.<init>(MechanismsConfiguration.java:50)
        at com.sk89q.craftbook.bukkit.MechanismsPlugin.onEnable(MechanismsPlugin.java:74)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:270)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:252)
        at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:320)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:299)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:258)
        at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:147)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:398)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)

**Comment by LadyCailin** [comment]
Comment by me4502 on 2012-11-18 06:31:25 UTC

Definately fixed in 1283

**Comment by LadyCailin** [comment]
Comment by chevyman142000 on 2012-11-18 06:35:14 UTC

Little different this time. 

01:32:34 [WARNING] Custom mob drop definitions failed to parse
com.sk89q.craftbook.mech.CustomDropManager$CustomDropParseException: Error on line 3 of drop definition file /srv/mc/plugins/CraftBookMechanisms/custom-mob-drops.txt: #
-> not found
        at com.sk89q.craftbook.mech.CustomDropManager.loadDropDefinitions(CustomDropManager.java:127)
        at com.sk89q.craftbook.mech.CustomDropManager.<init>(CustomDropManager.java:73)
        at com.sk89q.craftbook.MechanismsConfiguration.load(MechanismsConfiguration.java:86)
        at com.sk89q.craftbook.BaseConfiguration.<init>(BaseConfiguration.java:24)
        at com.sk89q.craftbook.MechanismsConfiguration.<init>(MechanismsConfiguration.java:50)
        at com.sk89q.craftbook.bukkit.MechanismsPlugin.onEnable(MechanismsPlugin.java:74)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:270)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:252)
        at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:320)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:299)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:258)
        at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:147)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:398)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)

**Comment by LadyCailin** [comment]
Comment by me4502 on 2012-11-18 06:37:03 UTC

That error is due to a custom drop being invalid - that's a normal error if you have a invalid drop.
