### ISSUE TITLE
The MIDI player is nonfunctional

### ISSUE THREAD

**Issue by LadyCailin** [LadyCailin/TestIssueUploader#274]
CMDBOOK-2108 - Reported by Sleepydragn1 on 2012-11-03 04:06:52 UTC

Whenever /midi [midi file name] or /intro is used, a note block will appear and the proper text messages will be sent to the user, but no notes will display or sound from it. /midi does technically work fine in stopping a currently "playing" midi, however.

[SEVERE] java.lang.IllegalStateException: sequencer not open
[SEVERE] 	at com.sun.media.sound.RealTimeSequencer.stop(Unknown Source)
[SEVERE] 	at com.sk89q.jinglenote.MidiJingleSequencer.run(MidiJingleSequencer.java:118)
[SEVERE] 	at com.sk89q.jinglenote.JingleNotePlayer.run(JingleNotePlayer.java:41)
[SEVERE] 	at java.lang.Thread.run(Unknown Source)

Is reported to console upon using either one of these commands.

It should be noted that this was working just fine for me until recently, that I'm currently running CraftBukkit Beta Build #2446 (1.4.2) and the most recent nightly builds (#523 of CommandBook and #1284 of WorldEdit), and that I checked with only WorldEdit, CommandBook, and PermissionsEx running to make sure that it wasn't due to any other plugins causing problems with CommandBook.

**Comment by LadyCailin** [comment]
Comment by xJoshJx on 2012-11-13 14:10:46 UTC

I have this too.

**Comment by LadyCailin** [comment]
Comment by darknavi on 2012-12-09 21:09:04 UTC

I am still getting this.  I'd love for this to be fixed :3

**Comment by LadyCailin** [comment]
Comment by BearFather on 2012-12-22 19:55:08 UTC

I would also love to see this fixed.  Since this was the feature a long time ago that got me to switch finally.

**Comment by LadyCailin** [comment]
Comment by me4502 on 2012-12-26 03:29:31 UTC

I had this issue in CRAFTBOOK with 1.3 I believe, i fixed it by rewriting the MIDI playing library to use the bukkit sound api instead of noteblocks.

I can't believe I wrote FalseBook.
